[{
    container: ".service-item-base-voice .experience-box",
    speakers: [{
        name: "小萍",
        enName: "aisxping",
        type: "普通话",
        language: "cn"
    }, {
        name: "小婧",
        enName: "aisjinger",
        type: "普通话",
        language: "cn"
    }, {
        name: "许久",
        enName: "aisjiuxu",
        type: "普通话",
        language: "cn"
    }, {
        name: "许小宝",
        enName: "aisbabyxu",
        type: "普通话",
        language: "cn"
    }]
}, {
    container: ".service-item-articles-voice .experience-box",
    speakers: [{
        name: "晓峰",
        enName: "x_xiaofeng",
        type: "普通话",
        language: "cn"
    }, {
        name: "晓燕",
        enName: "x_xiaoyan",
        type: "普通话",
        language: "cn"
    }, {
        name: "一峰",
        enName: "x_yifeng",
        type: "普通话",
        language: "cn"
    }, {
        name: "小梦",
        enName: "x_xiaomeng",
        type: "普通话",
        language: "cn"
    }, {
        name: "芳芳",
        enName: "x_xiaofang",
        type: "普通话",
        language: "cn"
    }]
}, {
    container: ".service-item-characteristic-voice .experience-box",
    speakers: [{
        name: "水哥",
        enName: "x_xiaoxi",
        type: "普通话",
        language: "cn"
    }, {
        name: "小媛",
        enName: "x_xiaoyuan",
        type: "普通话",
        language: "cn"
    }, {
        name: "逍遥子",
        enName: "x_xiaohou",
        type: "普通话",
        language: "cn"
    }, {
        name: "百合仙子",
        enName: "x_yiping",
        type: "普通话",
        language: "cn"
    }, {
        name: "小彬",
        enName: "x_xiaobin",
        type: "普通话",
        language: "cn"
    }, {
        name: "诺诺",
        enName: "x_xiaoai_Novel",
        type: "普通话",
        language: "cn"
    }, {
        name: "马叔",
        enName: "x_laoma",
        type: "普通话",
        language: "cn"
    }, {
        name: "小婧",
        enName: "x_jinger",
        type: "普通话",
        language: "cn"
    }, {
        name: "小华",
        enName: "x_xiaoyang_story",
        type: "普通话",
        language: "cn"
    }, {
        name: "小师",
        enName: "x_xiaoshi_CTS",
        type: "普通话",
        language: "cn"
    }, {
        name: "小魏",
        enName: "x_xiaowei",
        type: "普通话",
        language: "cn"
    }, {
        name: "小春",
        enName: "x_mengchun",
        type: "普通话",
        language: "cn"
    }, {
        name: "楠楠",
        enName: "x_nannan",
        type: "普通话",
        language: "cn"
    }, {
        name: "凯瑟琳",
        enName: "x_Catherine",
        type: "英语",
        defaultText: "iFLYTEK established in 1999. The intelligent speech technology of iFLYTEK, the core technology of the company, represents the top level in the world.",
        language: "en"
    }, {
        name: "John",
        enName: "x_John",
        type: "英语",
        defaultText: "iFLYTEK established in 1999. The intelligent speech technology of iFLYTEK, the core technology of the company, represents the top level in the world.",
        language: "en"
    }, {
        name: "小梅",
        enName: "x_xiaomei",
        type: "粤语",
        language: "cn"
    }, {
        name: "小蓉",
        enName: "x_xiaorong",
        type: "四川话",
        language: "cn"
    }, {
        name: "小强",
        enName: "x_xiaoqiang",
        type: "湖南话",
        language: "cn"
    }, {
        name: "小坤",
        enName: "x_xiaokun",
        type: "河南话",
        language: "cn"
    }, {
        name: "晓倩",
        enName: "x_xiaoqian",
        type: "东北话",
        language: "cn"
    }, {
        name: "小莹",
        enName: "x_xiaoying",
        type: "陕西话",
        language: "cn"
    }, {
        name: "晓琳",
        enName: "x_xiaolin",
        type: "台湾普通话",
        language: "cn"
    }, {
        name: "玉儿",
        enName: "x_yuer",
        type: "台湾普通话",
        language: "cn"
    }]
}, {
    container: ".service-item-star-voice .experience-box",
    speakers: [{
        name: "玲姐姐",
        enName: "x_xiaoling",
        type: "普通话",
        language: "cn"
    }, {
        name: "葛二爷",
        enName: "x_geyou_actor",
        type: "普通话",
        language: "cn"
    }, {
        name: "颖儿",
        enName: "x_liying_Actor",
        type: "普通话",
        language: "cn"
    }, {
        name: "宋宝宝",
        enName: "x_xiaosong",
        type: "普通话",
        language: "cn"
    }, {
        name: "小桃丸",
        enName: "x_xiaowanzi",
        type: "普通话",
        language: "cn"
    }, {
        name: "萌小新",
        enName: "x_xiaoxin",
        type: "普通话",
        language: "cn"
    }, {
        name: "马三爷",
        enName: "x_xiaoma",
        type: "普通话",
        language: "cn"
    }]
}]